# Generated by Django 3.0 on 2020-07-15 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=255)),
                ('product_name', models.CharField(max_length=255)),
                ('catagory_name', models.CharField(blank=True, max_length=255, null=True)),
                ('instock', models.BooleanField(default=True)),
                ('catagory_id', models.CharField(blank=True, max_length=255, null=True)),
                ('sub_catagory_name', models.CharField(blank=True, max_length=255, null=True)),
                ('discounted_price', models.CharField(blank=True, max_length=255, null=True)),
                ('vendor', models.CharField(choices=[('S', 'Shop Clues'), ('P', 'Paytm Mall'), ('T', 'Tata Cliq')], default='P', max_length=1)),
                ('price', models.CharField(max_length=255)),
                ('image_url', models.CharField(max_length=255)),
                ('product_url', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'unique_together': {('product_id', 'product_name')},
            },
        ),
    ]
